# Author: Veerendra K
# Description: An Ansible playbook to install necessary packages on MacOS

- name: Prepare Mac
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    # - import_tasks: tasks/prepare-mac.yml
    - import_tasks: tasks/dotfiles.yml