---
- name: Cloning dotfiles repository
  git:
    repo: https://github.com/veerendra2/dotfiles.git
    dest: "{{ user_home }}/projects/dotfiles"

- name: Find dotfiles
  find:
    file_type: file
    paths: "{{ user_home }}/projects/dotfiles"
    hidden: true
    file_type: file
    patterns: ".*"
    excludes:
      - .gitignore
      - .git
      - .config
      - .github
      - .*.swp
      - .gnupg"
  register: output

- name: Install dotfiles
  shell: "ln -sfn {{ item.path }} {{ user_home }}/{{ item.path | basename }}"
  with_items: "{{ output.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
