---
- name: Fetch homebrew version
  shell: brew --version
  register: output

- name: Display homebrew version
  debug:
    msg: "{{ output.stdout }}"

- name: Change ownership for `brew --prefix`
  shell: "chown -R {{ user_name }} $(brew --prefix)/*"
  become: yes

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Upgrade homebrew core packages
  homebrew:
    upgrade_all: yes

- name: Upgrade homebrew cask packages
  homebrew_cask:
    upgrade_all: yes

- name: Install homebrew core packages
  homebrew:
    name: "{{ brew_pkgs }}"
    state: present

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ brew_cask_apps }}"
    state: present
    install_options:
      - "appdir={{ brew_cask_appdir }}"

- name: Install pip packages
  pip:
    name: "{{ pip_pkgs }}"
    state: present
    executable: "pip3"

- name: Generate an OpenSSH keypair
  openssh_keypair:
    path: "{{ user_home }}/.ssh/id_rsa"
    force: no

- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ github_username_keys }}"

- name: Create projects directory
  file:
    name: "{{ user_home }}/projects"
    state: directory

- name: Cloning git repositories
  git:
    repo: "{{ item.value }}"
    dest: "{{ user_home }}/projects/{{ item.key }}"
  loop: "{{ lookup('dict', git_projects) }}"
  ignore_errors: yes
